import type { AppProps } from "next/app";
import Head from "next/head";

import favIcon from "../src/assets/favicon.ico";
import "../src/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favIcon.src} />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
